import json
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from datetime import datetime

from app.core.database import get_db
from app.models.schemas import TurnActionRequest, ChapterContent, StoryChoice
from app.graph.workflow import story_pipeline
from app.api.story import _preprocess_action, apply_state_changes, save_story_memory

router = APIRouter()

@router.post("/stream-turn")
async def stream_story_turn(request: TurnActionRequest, db=Depends(get_db)):
    """
    Streaming version of /turn.
    Uses LangGraph's astream_events to yield tokens as they are generated by the Writer.
    """
    story = await db.stories.find_one({"story_id": request.story_id})
    if not story:
        raise HTTPException(status_code=404, detail="Story not found")

    chapters = await db.chapters.find({"story_id": request.story_id}).sort("chapter_number", 1).to_list(None)
    if not chapters:
        raise HTTPException(status_code=400, detail="Story has no chapters")

    last_chapter = chapters[-1]
    new_chapter_number = last_chapter["chapter_number"] + 1

    character = story.get("character", {})
    action_context = await _preprocess_action(request, character)

    initial_state = {
        "story_config": story,
        "action_context": action_context,
        "past_summary": last_chapter.get("summary", ""),
        "chapter_title": "",
        "chapter_content": "",
        "chapter_summary": "",
        "tone": "ambient",
        "state_changes": {},
        "is_game_over": False,
        "choices": [],
        "error": None,
    }

    async def event_generator():
        final_state = None
        try:
            # We use astream_events to get granular events from the LangGraph execution
            async for event in story_pipeline.astream_events(initial_state, version="v2"):
                kind = event["event"]
                name = event["name"]
                
                # Check if this is a chunk from the Writer's LLM
                # Typically, ChatModels emit "on_chat_model_stream"
                if kind == "on_chat_model_stream":
                    # We only want to stream prose text. If it's generating JSON (like GameMaster), we might want to skip it.
                    # Usually, the writer_node uses plain text generation if structured output fails,
                    # but if it uses structured output, streaming might be harder.
                    # For safety, let's just stream any text chunk that doesn't look like JSON keys.
                    chunk = event["data"]["chunk"]
                    text = chunk.content
                    if isinstance(text, str) and text and not text.startswith('{"'):
                        yield f"data: {json.dumps({'type': 'token', 'text': text})}\n\n"
                
                # Intercept Critic feedback
                if kind == "on_chain_end" and name == "critic":
                    critic_output = event.get("data", {}).get("output", {})
                    if isinstance(critic_output, dict) and not critic_output.get("critic_passed", True):
                        feedback_msg = critic_output.get('critic_feedback', 'Phát hiện lỗi logic. Đang viết lại...')
                        alert_text = f"\\n\\n> **[HỆ THỐNG KIỂM DUYỆT]** {feedback_msg}\\n\\n"
                        yield f"data: {json.dumps({'type': 'token', 'text': alert_text})}\n\n"
                        
                # Store the final state when the graph finishes
                if kind == "on_chain_end" and name == "LangGraph":
                    final_state = event["data"]["output"]

        except Exception as e:
            print(f"[STREAM ERROR] {e}")
            yield f"data: {json.dumps({'type': 'error', 'message': str(e)})}\n\n"
            return

        if not final_state:
            yield f"data: {json.dumps({'type': 'error', 'message': 'No final state produced'})}\n\n"
            return

        # 5. Extract Output and Save
        chapter_title = final_state.get("chapter_title", f"Chương {new_chapter_number}")
        chapter_content = final_state.get("chapter_content", "Failed to generate text.")
        chapter_summary = final_state.get("chapter_summary", "")
        choices = final_state.get("choices", [])
        state_changes = final_state.get("state_changes", {})
        is_game_over = final_state.get("is_game_over", False)
        tone = final_state.get("tone", "ambient")

        new_chapter = ChapterContent(
            story_id=request.story_id,
            chapter_number=new_chapter_number,
            chapter_title=chapter_title,
            content=chapter_content,
            summary=chapter_summary,
            tone=tone,
            choices=[StoryChoice(**c) for c in choices] if choices else [],
        )

        await db.chapters.insert_one(new_chapter.model_dump())

        if request.action_type == "move":
            target = request.target_location_id or request.custom_action
            if target:
                state_changes["current_location_id"] = target

        if state_changes:
            await apply_state_changes(request.story_id, state_changes, new_chapter_number)

        await db.stories.update_one(
            {"story_id": request.story_id},
            {"$set": {"current_chapter": new_chapter_number, "updated_at": datetime.utcnow()}}
        )

        try:
            from app.services.embedding import get_text_embedding
            summary_embedding = await get_text_embedding(chapter_summary)
            await save_story_memory(
                story_id=request.story_id,
                chapter_number=new_chapter_number,
                text_content=chapter_content[:2000],
                embedding_vector=summary_embedding,
            )
        except Exception as e:
            print(f"[WARNING] Failed to save memory: {e}")

        updated_story = await db.stories.find_one({"story_id": request.story_id})
        updated_story.pop("_id", None)

        # Yield the final payload
        final_payload = {
            "type": "done",
            "chapter": new_chapter.model_dump(),
            "config": updated_story
        }
        
        # Serialize datetime correctly
        def datetime_handler(x):
            if isinstance(x, datetime):
                return x.isoformat()
            raise TypeError("Unknown type")
            
        yield f"data: {json.dumps(final_payload, default=datetime_handler)}\n\n"

    return StreamingResponse(event_generator(), media_type="text/event-stream")
